registryItems:
  applications:
  - {struts2-scenario: nq 0}
  instances:
  - {struts2-scenario: 1}
  operationNames:
  - struts2-scenario: [/struts2-scenario/struts2/case.action]
segmentItems:
- applicationCode: struts2-scenario
  segmentSize: 1
  segments:
  - segmentId: not null
    spans:
    - operationName: /struts2-scenario/struts2/case.action
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 15
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/struts2-scenario/struts2/case.action'}
      - {key: http.method, value: GET}